### PR TITLE
Remove `stylelint-codeguide` and update `stylelint-stylistic`

### PR DESCRIPTION
**Pull request by firefoxic**
> Which issue, if any, is this issue related to?

[Reference](https://github.com/stylelint/stylelint/pull/7419).

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

### CODE REVIEW

**Review by ybiquitous — COMMENTED** [review]
Thank you! Just to confirm, do you want to stick in the name `stylelint-stylistic`? Since the package name is `@stylistic/stylelint-plugin`, I'm a bit worried that it'd confuse people.

**Comment by firefoxic** [comment]
> Thank you! Just to confirm, do you want to stick in the name `stylelint-stylistic`? Since the package name is `@stylistic/stylelint-plugin`, I'm a bit worried that it'd confuse people.

All the links in the list lead to GitHub repositories, which is why I decided to follow this pattern. But it's probably better to specify a package instead of a repository.

**Review by ybiquitous — APPROVED** [review]
Make sense. We'd like to keep consistency.

Thank you again! 👍🏼

**Comment by firefoxic** [comment]
@ybiquitous Although, now I noticed that the first one in the plugin list links to a GitHub repository, but the link text uses the name of the npm package. Maybe in my case it would make sense to do it that way too? 🤔

https://github.com/stylelint/awesome-stylelint/blob/21a13b1290d8b04cc82e59a326d8f4a63b486770/README.md?plain=1#L76

**Comment by ybiquitous** [comment]
@firefoxic Oh, I missed it. If a link refers to a npm package, the package name might be clearer. Can you update the link text, including other packages?

**Pull request merged**
